name: Test Docker Image

on:
  push:
    paths:
      - 'Dockerfile'
  pull_request:
    paths:
      - 'Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker buildx build --platform=linux/amd64,linux/arm64,linux/arm/v7 -t my-fastapi-app .

      - name: Test Docker image
        run: scripts/test_docker_image.sh

      - name: Publish Docker image to Docker Hub
        if: ${{ job.status == 'success' }}
        env:
          DOCKER_USER_NAME: ${{ secrets.DOCKER_USER_NAME }}
          DOCKER_USER_PASSWORD: ${{ secrets.DOCKER_USER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER_NAME -p $DOCKER_USER_PASSWORD
          docker tag my-fastapi-app $DOCKER_USER_NAME/my-fastapi-app
          docker push $DOCKER_USER_NAME/my-fastapi-app
